### ISSUE TITLE
Define root folder path of a new Node

### ISSUE THREAD

**Issue by coxy17** [divengine/div-nodes#5]
Hi

Is it possible to specify a different directory other than where the php file the new node is ran?

`$db = new nodes("database/contacts");`

i have tried using '../' which works ok but was just curious 

`$db = new nodes("../database/contacts");`

something like...
`$db = new nodes("C:/wamp/www/database/contacts");`

thanks

**Comment by rafageist** [comment]
Hi

There is a constant that defines the root of your data. You must define it before loading `divengine\nodes` or before first use. This is like telling `nodes` where our `database` is:

```php
<?php

// slash at the end is a good practice
define('DIV_NODES_ROOT', 'C:/wamp/www/database/'); 

include __DIR__ . '/../vendor/autoload.php';

$db = new nodes("contacts");
```


>[!WARNING]
> If you are curious you will see that you can put an empty value or "/", but this is not recommended because what you want is to give `nodes` a location with data and not the entire hard drive. I say this because maybe you want to work with 2 databases at the same time, and the constant only allows you one root path. Be careful with these kinds of tricks.

Regards

**Comment by coxy17** [comment]
Hi

Ok thanks that makes sense, thanks for the explanation.

Nick
